In [1]:
import os
curr_dir = os.getcwd()
dataset_dir_path = os.path.join(curr_dir,'Pianalytix_Datasets')

In [2]:
print(os.listdir(dataset_dir_path))

['cpdata.csv', 'Fertilizer.csv', 'FertilizerData.csv', 'FinalData.csv', 'MergeFileCrop.csv', 'Rainfall.csv']


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\Nikhil\anaconda3\envs\tf-gpu\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Nikhil\anaconda3\envs\tf-gpu\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
fertilizerdata = pd.read_csv(os.path.join(dataset_dir_path,'FertilizerData.csv'))
cpdata = pd.read_csv(os.path.join(dataset_dir_path,'cpdata.csv'))

In [5]:
fertilizerdata.head(10)

Unnamed: 0         Crop   N   P   K   pH  soil_moisture
0           0         rice  80  40  40  5.5             30
1           3        maize  80  40  20  5.5             50
2           5     chickpea  40  60  80  5.5             60
3          12  kidneybeans  20  60  20  5.5             45
4          13   pigeonpeas  20  60  20  5.5             45
5          14    mothbeans  20  40  20  5.5             30
6          15     mungbean  20  40  20  5.5             80
7          18    blackgram  40  60  20  5.0             60
8          24       lentil  20  60  20  5.5             90
9          60  pomegranate  20  10  40  5.5             30

In [6]:
cpdata.head(10)

temperature   humidity        ph    rainfall label
0    20.879744  82.002744  6.502985  202.935536  rice
1    21.770462  80.319644  7.038096  226.655537  rice
2    23.004459  82.320763  7.840207  263.964248  rice
3    26.491096  80.158363  6.980401  242.864034  rice
4    20.130175  81.604873  7.628473  262.717340  rice
5    23.058049  83.370118  7.073454  251.055000  rice
6    22.708838  82.639414  5.700806  271.324860  rice
7    20.277744  82.894086  5.718627  241.974195  rice
8    24.515881  83.535216  6.685346  230.446236  rice
9    23.223974  83.033227  6.336254  221.209196  rice

In [7]:
fertilizerdata.describe()

Unnamed: 0           N           P           K         pH  \
count   22.000000   22.000000   22.000000   22.000000  22.000000   
mean    48.681818   50.454545   45.681818   48.181818   5.409091   
std     33.540858   36.315715   32.634172   51.698426   0.590326   
min      0.000000   20.000000   10.000000   10.000000   4.000000   
25%     14.250000   20.000000   20.000000   20.000000   5.500000   
50%     61.500000   30.000000   40.000000   30.000000   5.500000   
75%     72.750000   80.000000   60.000000   50.000000   5.500000   
max     95.000000  120.000000  125.000000  200.000000   6.500000   

       soil_moisture  
count      22.000000  
mean       46.363636  
std        20.827055  
min        15.000000  
25%        30.000000  
50%        45.000000  
75%        60.000000  
max        90.000000

In [8]:
fertilizerdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Unnamed: 0     22 non-null     int64  
 1   Crop           22 non-null     object 
 2   N              22 non-null     int64  
 3   P              22 non-null     int64  
 4   K              22 non-null     int64  
 5   pH             22 non-null     float64
 6   soil_moisture  22 non-null     int64  
dtypes: float64(1), int64(5), object(1)
memory usage: 1.3+ KB


In [9]:
cpdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3100 entries, 0 to 3099
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   temperature  3100 non-null   float64
 1   humidity     3100 non-null   float64
 2   ph           3100 non-null   float64
 3   rainfall     3100 non-null   float64
 4   label        3100 non-null   object 
dtypes: float64(4), object(1)
memory usage: 121.2+ KB


In [10]:
fertilizerdata.columns

Index(['Unnamed: 0', 'Crop', 'N', 'P', 'K', 'pH', 'soil_moisture'], dtype='object')

In [11]:
fertilizerdata.drop('Unnamed: 0',axis = 1,inplace= True)

In [12]:
fertilizerdata.head(10)

Crop   N   P   K   pH  soil_moisture
0         rice  80  40  40  5.5             30
1        maize  80  40  20  5.5             50
2     chickpea  40  60  80  5.5             60
3  kidneybeans  20  60  20  5.5             45
4   pigeonpeas  20  60  20  5.5             45
5    mothbeans  20  40  20  5.5             30
6     mungbean  20  40  20  5.5             80
7    blackgram  40  60  20  5.0             60
8       lentil  20  60  20  5.5             90
9  pomegranate  20  10  40  5.5             30

In [13]:
fertilizerdata.rename(columns={"Crop":"label"} , inplace = True)

In [14]:
fertilizerdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   label          22 non-null     object 
 1   N              22 non-null     int64  
 2   P              22 non-null     int64  
 3   K              22 non-null     int64  
 4   pH             22 non-null     float64
 5   soil_moisture  22 non-null     int64  
dtypes: float64(1), int64(4), object(1)
memory usage: 1.2+ KB


In [15]:
df = pd.merge(cpdata,fertilizerdata,on="label")

In [16]:
df

temperature   humidity        ph    rainfall       label    N   P   K  \
0       20.879744  82.002744  6.502985  202.935536        rice   80  40  40   
1       21.770462  80.319644  7.038096  226.655537        rice   80  40  40   
2       23.004459  82.320763  7.840207  263.964248        rice   80  40  40   
3       26.491096  80.158363  6.980401  242.864034        rice   80  40  40   
4       20.130175  81.604873  7.628473  262.717340        rice   80  40  40   
...           ...        ...       ...         ...         ...  ...  ..  ..   
1095    25.287846  89.636679  6.765095   58.286977  watermelon  100  10  50   
1096    26.638386  84.695469  6.189214   48.324286  watermelon  100  10  50   
1097    25.331045  84.305338  6.904242   41.532187  watermelon  100  10  50   
1098    26.897502  83.892415  6.463271   43.971937  watermelon  100  10  50   
1099    26.986037  89.413849  6.260839   58.548767  watermelon  100  10  50   

       pH  soil_moisture  
0     5.5             30  
1     5.5             30  
2     5.5             30  
3     5.5             30  
4     5.5             30  
...   ...            ...  
1095  5.5             70  
1096  5.5             70  
1097  5.5             70  
1098  5.5             70  
1099  5.5             70  

[1100 rows x 10 columns]

In [17]:
df.describe()

temperature     humidity           ph     rainfall            N  \
count  1100.000000  1100.000000  1100.000000  1100.000000  1100.000000   
mean     25.793353    82.208241     6.310789   103.513966    55.454545   
std       5.808913    13.067373     0.570641    56.914930    35.012967   
min       8.825675    45.022364     4.507524    20.211267    20.000000   
25%      22.520446    80.328365     5.915424    68.195767    20.000000   
50%      25.413870    85.030605     6.294910   100.565794    50.000000   
75%      28.928470    91.611997     6.685398   112.732469   100.000000   
max      43.675493    94.998975     7.995849   298.560117   100.000000   

                 P            K           pH  soil_moisture  
count  1100.000000  1100.000000  1100.000000    1100.000000  
mean     46.818182    67.272727     5.409091      41.363636  
std      41.866850    63.859905     0.792888      17.075930  
min      10.000000    10.000000     4.000000      15.000000  
25%      10.000000    30.000000     5.000000      30.000000  
50%      40.000000    50.000000     5.500000      40.000000  
75%      75.000000    50.000000     6.000000      60.000000  
max     125.000000   200.000000     6.500000      70.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1100 entries, 0 to 1099
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   temperature    1100 non-null   float64
 1   humidity       1100 non-null   float64
 2   ph             1100 non-null   float64
 3   rainfall       1100 non-null   float64
 4   label          1100 non-null   object 
 5   N              1100 non-null   int64  
 6   P              1100 non-null   int64  
 7   K              1100 non-null   int64  
 8   pH             1100 non-null   float64
 9   soil_moisture  1100 non-null   int64  
dtypes: float64(5), int64(4), object(1)
memory usage: 94.5+ KB


In [19]:
df['label'].value_counts()

banana         100
pomegranate    100
mango          100
orange         100
maize          100
rice           100
watermelon     100
muskmelon      100
papaya         100
grapes         100
apple          100
Name: label, dtype: int64

In [20]:
df.isnull().sum(axis = 0)

temperature      0
humidity         0
ph               0
rainfall         0
label            0
N                0
P                0
K                0
pH               0
soil_moisture    0
dtype: int64

In [21]:
df['N'] = df['N'].astype('float64')
df['P'] = df['P'].astype('float64')
df['K'] = df['K'].astype('float64')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1100 entries, 0 to 1099
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   temperature    1100 non-null   float64
 1   humidity       1100 non-null   float64
 2   ph             1100 non-null   float64
 3   rainfall       1100 non-null   float64
 4   label          1100 non-null   object 
 5   N              1100 non-null   float64
 6   P              1100 non-null   float64
 7   K              1100 non-null   float64
 8   pH             1100 non-null   float64
 9   soil_moisture  1100 non-null   int64  
dtypes: float64(8), int64(1), object(1)
memory usage: 94.5+ KB


In [23]:
column_names = list(df.columns)
print(column_names)

['temperature', 'humidity', 'ph', 'rainfall', 'label', 'N', 'P', 'K', 'pH', 'soil_moisture']


In [24]:
X = df.loc[:,['temperature', 'humidity', 'ph', 'rainfall', 'N', 'P', 'K', 'pH', 'soil_moisture']].values
y = df.loc[: , 'label'].values

In [25]:
X

array([[20.87974371, 82.00274423,  6.50298529, ..., 40.        ,
         5.5       , 30.        ],
       [21.77046169, 80.31964408,  7.03809636, ..., 40.        ,
         5.5       , 30.        ],
       [23.00445915, 82.3207629 ,  7.84020714, ..., 40.        ,
         5.5       , 30.        ],
       ...,
       [25.3310446 , 84.30533791,  6.90424171, ..., 50.        ,
         5.5       , 70.        ],
       [26.89750174, 83.89241484,  6.46327108, ..., 50.        ,
         5.5       , 70.        ],
       [26.98603693, 89.4138489 ,  6.26083896, ..., 50.        ,
         5.5       , 70.        ]])

In [26]:
X.shape

(1100, 9)

In [27]:
y

array(['rice', 'rice', 'rice', ..., 'watermelon', 'watermelon',
       'watermelon'], dtype=object)

In [28]:
y.shape

(1100,)

In [29]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
sc = StandardScaler()
sc.fit(X)
X = sc.transform(X)
le = LabelEncoder()
y = le.fit_transform(y)

In [30]:
X

array([[-0.84625886, -0.01573312,  0.33696037, ..., -0.42726547,
         0.11470787, -0.66577955],
       [-0.69285268, -0.14459343,  1.27512338, ..., -0.42726547,
         0.11470787, -0.66577955],
       [-0.48032433,  0.0086148 ,  2.68139342, ..., -0.42726547,
         0.11470787, -0.66577955],
       ...,
       [-0.07962221,  0.16055641,  1.04044783, ..., -0.27060146,
         0.11470787,  1.67776447],
       [ 0.19016486,  0.12894249,  0.26733294, ..., -0.27060146,
         0.11470787,  1.67776447],
       [ 0.20541306,  0.55167058, -0.08757341, ..., -0.27060146,
         0.11470787,  1.67776447]])

In [31]:
y

array([ 9,  9,  9, ..., 10, 10, 10])

In [32]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y)

In [33]:
def check_prediction_accuracy(y_preds,y_true):
    from sklearn.metrics import f1_score , accuracy_score
    print(f"f1 score  {f1_score(y_preds,y_true,average='macro')}")
    print(f"accuracy score {accuracy_score(y_preds,y_true)}")

In [37]:
from sklearn.svm import SVC
svc_clf = SVC()
svc_clf.fit(X_train,y_train)
predictions = svc_clf.predict(X_test)
check_prediction_accuracy(predictions,y_test)

f1 score  1.0
accuracy score 1.0


In [38]:
from sklearn.tree import DecisionTreeClassifier
dtree_clf = DecisionTreeClassifier()
dtree_clf.fit(X_train,y_train)
predictions = dtree_clf.predict(X_test)
check_prediction_accuracy(predictions,y_test)

f1 score  1.0
accuracy score 1.0


In [39]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train,y_train)
predictions = rf_clf.predict(X_test)
check_prediction_accuracy(predictions,y_test)

f1 score  1.0
accuracy score 1.0
